plugins:
filters:
  comments: true
  allowlist:
    allowlistConfigPaths:
      - .textlint/allowlist.yml
rules:
  preset-ja-technical-writing:
    sentence-length: 100
    max-kanji-continuous-len:
      max: 6
      allow: []
    no-mix-dearu-desumasu: false
    no-exclamation-question-mark: false
    no-doubled-joshi:
      strict: false
  preset-japanese:
    sentence-length:
      max: 100
    max-ten:
      max: 4
    no-doubled-joshi:
      strict: false
  preset-ja-spacing:
    ja-space-between-half-and-full-width:
      space:
        - alphabets
        - numbers
  no-mixed-zenkaku-and-hankaku-alphabet: true
  common-misspellings: true
  spellcheck-tech-word: true
  prh:
    rulePaths:
      - ./.textlint/dict/prh.yml
  "@proofdict/proofdict":
    dictURL: "https://atsushifx.github.io/proof-dictionary/"
