plugins:
filters:
  comments: true
  allowlist:
    allowlistConfigPaths:
      - .textlint/allowlist.yml
rules:
  preset-japanese: true
  "@textlint-ja/preset-ai-writing": true
  preset-ja-spacing:
    ja-space-between-half-and-full-width:
      space:
        - alphabets
        - numbers
  sentence-length:
    max: 100
  no-mixed-zenkaku-and-hankaku-alphabet: true
  common-misspellings: true
  prh:
    rulePaths:
      - ./.textlint/dict/prh.yml
  "@proofdict/proofdict":
    dictURL: "https://atsushifx.github.io/proof-dictionary/"
