# src: ./configs/textlintrc.yaml
# @(#) : yaml type textlint config
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

plugins: {}
filters:
  comments: true
  allowlist:
    allowlistConfigPaths:
      - .textlint/allowlist.yml
rules:
  preset-japanese:
    sentence-length:
      max: 100
  "@textlint-ja/preset-ai-writing": true
  preset-ja-spacing:
    ja-space-between-half-and-full-width:
      space:
        - alphabets
        - numbers
  ja-hiraku: true
  common-misspellings: true
  ja-no-orthographic-variants: true
  "@textlint-ja/textlint-rule-no-synonyms": true
  no-mixed-zenkaku-and-hankaku-alphabet: true
  "@proofdict/proofdict":
    dictURL: "https://atsushifx.github.io/proof-dictionary/"
  prh:
    rulePaths:
      - ./.textlint/dict/prh.yml
